Linter Name: Pylint
Linter Module: pylint
CWD Linter Server: /home/bot/AAMeineSachen/FL3XX/BRIGHT-reporting
sys.path used to run Linter:
   /home/bot/.vscode/extensions/ms-python.pylint-2022.2.0/bundled/linter
   /home/bot/anaconda3/envs/bright/lib/python310.zip
   /home/bot/anaconda3/envs/bright/lib/python3.10
   /home/bot/anaconda3/envs/bright/lib/python3.10/lib-dynload
   /home/bot/.local/lib/python3.10/site-packages
   /home/bot/anaconda3/envs/bright/lib/python3.10/site-packages
   /home/bot/.vscode/extensions/ms-python.pylint-2022.2.0/bundled/libs
Settings used to run Linter:
[
    {
        "workspace": "file:///home/bot/AAMeineSachen/FL3XX/BRIGHT-reporting",
        "trace": "error",
        "args": [],
        "severity": {
            "convention": "Information",
            "error": "Error",
            "fatal": "Error",
            "refactor": "Hint",
            "warning": "Warning",
            "info": "Information"
        },
        "path": [],
        "interpreter": [
            "/home/bot/anaconda3/envs/bright/bin/python"
        ]
    }
]

pylint --reports=n --output-format=json --from-stdin /home/bot/AAMeineSachen/FL3XX/BRIGHT-reporting/app/etl/ps_etl.py
CWD Linter: /home/bot/AAMeineSachen/FL3XX/BRIGHT-reporting
[Error - 7:04:57 AM] PYLINTHOME is now '/home/bot/.cache/pylint' but obsolescent '/home/bot/.pylint.d' is found; you can safely remove the latter

file:///home/bot/AAMeineSachen/FL3XX/BRIGHT-reporting/app/etl/ps_etl.py :
[
    {
        "type": "error",
        "module": "app.etl.ps_etl",
        "obj": "",
        "line": 32,
        "column": 0,
        "endLine": 32,
        "endColumn": 68,
        "path": "app/etl/ps_etl.py",
        "symbol": "import-error",
        "message": "Unable to import 'helpers.helpers'",
        "message-id": "E0401"
    },
    {
        "type": "error",
        "module": "app.etl.ps_etl",
        "obj": "",
        "line": 33,
        "column": 0,
        "endLine": 33,
        "endColumn": 53,
        "path": "app/etl/ps_etl.py",
        "symbol": "import-error",
        "message": "Unable to import 'helpers.read_config'",
        "message-id": "E0401"
    }
]

